CREATE TABLE staging.distribution_center_database (
    distribution_center_id     VARCHAR(50),
    distribution_center_name   VARCHAR(255),
    warehouse_type              VARCHAR(100),
    region                       VARCHAR(100),
    city                         VARCHAR(100),
    country                      VARCHAR(100),
    manager_id                   VARCHAR(50),
    product_id                   VARCHAR(50),
    storage_type                 VARCHAR(50),
    inventory_units              INTEGER,
    storage_capacity_units       INTEGER,
    occupied_capacity_units      INTEGER,
    utilization_pct              NUMERIC(5,2),
    inbound_shipments            INTEGER,
    outbound_shipments           INTEGER,
    orders_processed             INTEGER,
    avg_processing_time_hours    NUMERIC(5,2),
    dock_doors                   INTEGER,
    employees                    INTEGER,
    operating_shift               VARCHAR(20),
    status                        VARCHAR(50),
    record_date                   DATE,
    on_time_dispatch_pct          NUMERIC(5,2),
    damaged_units                 INTEGER,
    stockout_flag                 VARCHAR(10),
    last_inventory_audit_date     DATE
);
